### ISSUE TITLE
Marketing of Armonaut

### ISSUE THREAD

**Issue by SethMichaelLarson** [armonaut/armonaut.io#5]
## Flexible Continuous Integration Topology
- Continuous Integration isn't one-size fits all, even between projects owned by the same team!
- By selling by compute-unit rather than container you save time and money by specifying exactly what resources your builds require.
- Documentation and linting jobs don't require 8GB of RAM, so why pay for it?

```yaml
jobs:
  # Documentation job, only needs 1GB RAM
  - compute_units: 1
    install:
      - pip install sphinx
    script:
      - make docs

  # Integration testing job, more RAM required!
  - compute_units: 4
    install:
      - pip install flask pytest-flask
    script:
      - make test
```

## Scale your Continuous Integration Performance
- Adding new compute units is as easy as dragging a scroll bar in options. Instantly speed up build completion time
- Jobs start in under a minute no matter the load. No more queuing for hours!

## Continuous Integration Metrics
- Build time, trends, analysis of each contributor, branch, pull request, and file for churn statistics.
- Off by default costs an additional $30/month

## Unrelenting Force
- Largest compute instance has 16GB of RAM and 8 vCPUs for unmatched performance
- Can handle resource-heavy jobs that can't be done with other Continuous Integration services
- Comparison of build time for the Linux source code with Armonaut, Circle CI, Travis
- Maximum job time is 55 minutes

## Customizable Caching to speed up jobs
- Setup cache rules per-job within `armonaut.yml`.
- Cache dependencies to speed up jobs

## Supports all major Code Hosting platforms
- Provides service for GitHub, GitLab, and BitBucket all under one roof to save on costs for teams with multiple code hosts.

## Notifications
- Slack, Gitter, Email, Commit Statuses

## Debugging Tools
- SSH connection into real-time builds.
- One-off compute instances to debug inside of with CLI

## Built for Open Source
- Open Source is a vital part of the current Software Ecosystem we live in. You'd be hard-pressed to find a single piece of software that hasn't benefited from the existence of Open Source software. Armonaut aims to give back to critical Open Source teams and projects.
